### ISSUE TITLE
GLua api definitions

### ISSUE THREAD

**Issue by luttje** [Lexicality/applejack#91]
Yo Lexi, long time no speak! How are you?

I see you are/were in the process of collecting the GLua types for auto completion in vscode. Look no further, I've hacked this together:
https://github.com/luttje/glua-api-snippets

Hope it helps!

Luttje aka tjjokerr

**Comment by Lexicality** [comment]
Hej!
Thanks for thinking of me, but I got [libgmod](https://github.com/Lexicality/libgmod) working a few months ago and have been pretty happy with it.
Glad to see you're still around, maybe hit me up on steam or something to chat?
